# -*- coding: utf-8 -*-
"""lab 2 NLP.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CpwguijJuQ8jw_AmIkpZV5uUveCh09ZD
"""

import re

text = """
Sara Ahmed is a software developer who lives in Saudi Arabia.
She was born on 1985-09-15 and can be reached at sara.ahmed@example.com.
For inquiries, contact +966512345678 or visit our website.
"""

pattern = r'\b[A-Z][a-z]+\b'

match_pattern = re.findall(pattern, text)

print("Text:", text)
print("match pattern:", match_pattern)

import re

sample_text = "username : A90"

pattern = r'\b[A-Z]\w+\b'

match_pattern = re.findall(pattern, sample_text)

print("Text:", sample_text)
print("match pattern:", match_pattern)

import re

text = """
Sara Ahmed is a software developer who lives in Saudi Arabia.
She was born on 1985-09-15 and can be reached at sara.ahmed@example.com.
For inquiries, contact +966512345678 or visit our website.
"""

pattern = r'\b[A-Z][a-z]+\s[A-Z][a-z]+\b'

match_pattern = re.findall(pattern, text)

print("Text:", text)
print("match pattern:", match_pattern)

import re

sample_text = "Sara was playing"

pattern = r'[A-Za-z]+ing$'

match_pattern = re.findall(pattern, sample_text)

print("Text:", sample_text)
print("match pattern:", match_pattern)

import re

sample_text = "Sara was playing"

pattern = r'\b[A-Za-z]+\b'

match_pattern = re.findall(pattern, sample_text)

print("Text:", sample_text)
print("match pattern:", match_pattern)

import re

text = """
Sara Ahmed is a software developer who lives in Saudi Arabia.
She was born on 1985-09-15 and can be reached at sara.ahmed@example.com.
For inquiries, contact +966512345678 or visit our website.
"""

pattern = r'\b[S][a-z]{2}\b'

match_pattern = re.findall(pattern, text)

print("Text:", text)
print("match pattern:", match_pattern)

import re

text = """
Sara Ahmed is a software developer who lives in Saudi Arabia.
She was born on 1985-09-15 and can be reached at sara.ahmed@example.com.
For inquiries, contact +966512345678 or visit our website.
"""

pattern = r'\b[S][a-z]{2,3}\b'

match_pattern = re.findall(pattern, text)

print("Text:", text)
print("match pattern:", match_pattern)

import re

text = """
Sara Ahmed is a software developer who lives in Saudi Arabia.
She was born on 1985-09-15 and can be reached at sara.ahmed@example.com.
For inquiries, contact +966512345678 or visit our website.
"""

pattern = r'\b[a-z][a-z0-9._-]*@[a-z0-9.-]+\.(?:sa|com)\b'

match_pattern = re.findall(pattern, text)

print("Text:", text)
print("match pattern:", match_pattern)

import re

pattern = r'@[a-zA-Z0-9_]{5,15}'

sample_text = "First username : @user_123. Second username: @invalid-user. Third username: @Validuser."

matches = re.findall(pattern, sample_text)

print(matches)

import re

text = """
Sara was born on 1985-09-15.
Another date is 2024-01-01.
"""

pattern = r'\b\d{4}-\d{2}-\d{2}\b'

match_pattern = re.findall(pattern, text)

print("Text:", text)
print("match pattern:", match_pattern)

import re

text = "Sara Ahmed"

pattern = r"Sara"

result = re.search(pattern, text)

print(result)

import re

text = "Sara Ahmed Sara"

pattern = r"Sara"

result = re.findall(pattern, text)

print(result)

import re

text = "Sara Ahmed"

pattern = r"Sara"

result = re.match(pattern, text)

print(result)

import re

text = "Sara Ahmed 1985-09-15 +966512345678"

result = re.split(r'\s', text)

print(result)

result = re.split(r'[\s\d\-\+]+', text)
print(result)

import re

text = "Sara was born in 1985 and her phone is 966512345678"

result = re.sub(r'\d', ' ', text)

print(result)